sonar.projectKey=sampratigaurav_syncwatch
sonar.organization=sampratigaurav

sonar.projectName=syncwatch

sonar.sources=client/src,server/src,shared,extension/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

# Ignore test coverage requirements since we aren't uploading coverage reports yet
sonar.coverage.exclusions=**/*

sonar.sourceEncoding=UTF-8
